### ISSUE TITLE
Issue with tiff2pdf conversionnodejs

### ISSUE THREAD

**Issue by manuelgeorge** [cwhite911/tiff2pdf#2]
Hi white ,

I'm trying to do  a conversion from tiff to pdf file using the module tiff2pdf(1.0.2)

PDF file is not generating with the sample test code and i'm getting some error.I have tried with the test.js(in downloaded package) and still getting the same error.In console it  is saying  successful but pdf file is not generating.I have printed the result object and getting the same error as mentioned below.

{ message: 'error',
  code: 
   { Error: spawn tiff2pdf ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
     errno: 'ENOENT',
     code: 'ENOENT',
     syscall: 'spawn tiff2pdf',
     path: 'tiff2pdf',
     spawnargs: [ '-o', '\\pdfs\\test.pdf', 'test.tiff' ] } }
{ message: 'close', code: -4058 }

please let me know if there is any dependency in npm version or OS.

OS windows 7 64 bit
npm 5.5.1
IDE- Webstorm(Evaluation Version)

Code -

var tiff2pdf=require("tiff2pdf")

tiff2pdf('test.tiff', '/pdfs', function(result){
    console.log(result);
});

I would be very much  grateful to you if you can help me at the earliest.

Regards,
Manuel George

**Comment by cwhite911** [comment]
@manuelgeorge make sure the path is correct to your file and output directory, and that the output directory exists.

**Comment by kennylbj** [comment]
Same issue

**Comment by GiovaniFerraroTrivelli** [comment]
Same issue
